### ISSUE TITLE
Support for SSL using self-signed certs

### ISSUE THREAD

**Issue by zipwiz** [emiloberg/liferay-ddmtool#6]
I tried to use this tool to fetch built structure meta data from a dev host which is reachable only via https, but has only self-signed dummy certs installed. I receive this message:

`Unknown error: {"code":"DEPTH_ZERO_SELF_SIGNED_CERT"}`

This seems to be a node.js problem but can be overcome using the right modules and implementation (as it seems).

Is it possible to extend liferay-ddmtool such that thid problem can be bypassed at least by explicit configuration? Something like "allowSelfSignedCerts : true"?

**Comment by zipwiz** [comment]
Additional resources:
https://github.com/request/request/issues/418

**Comment by emiloberg** [comment]
Looks like Node changed a bit around 0.10.x

> rejectUnauthorized: If true, the server certificate is verified against the list of supplied CAs. An 'error' event is emitted if verification fails. Verification happens at the connection level, before the HTTP request is sent. Default true.
- [http://nodejs.org/docs/v0.10.4/api/https.html](http://nodejs.org/docs/v0.10.4/api/https.html#https_https_request_options_callback)

Could you test one thing for me: Open the `index.js` and add the following line at the very top:
```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
```

Does that solve it?

**Comment by zipwiz** [comment]
Thanks... result is:

`Getting data from server`
`Downloading id's`

`Downloading list of sites`

`Error`
`Error: Could not find any sites`

I interpret this as "yes, this problem is solved" (although having another one now...)

**Comment by emiloberg** [comment]
Ouch! Could I ask you to add a new issue (so I can keep this for implementing a nicer way of accepting self signed certs).

**Comment by zipwiz** [comment]
OK, I will try some title and content... I hope to meet your expectations ;-)

**Comment by emiloberg** [comment]
Just copy paste the previous message and I'm happy ;)

**Comment by zipwiz** [comment]
take a look...

**Comment by zipwiz** [comment]
or did you mean the full ddm-tool reply?

**Comment by emiloberg** [comment]
Haha, I meant the `Error: Could not find any sites` problem, as I think that's a separate issue, but no problems, let's do it here.

If you find me on skype: emil.oberg or hangout: emil.oberg@gmail.com It might be easier to debug the problem.

**Comment by zipwiz** [comment]
I will come back as necessary, but I think that the problem is not caused by ddm-tool, but by my local setup. If that is succuessfully excluded as a possible reason, I will aks again here. Thanks for the offer however :-)

**Comment by emiloberg** [comment]
Perfect! Don't hesitate to come back if the error persist!
