### ISSUE TITLE
Handle self-signed SSL server certificates

### ISSUE THREAD

**Issue by zipwiz** [emiloberg/liferay-ddmtool#7]
Currently ddm-tool stumbles when trying to connect to a server which uses SSL but has only a self-signed ("dummy") certificate installed. This is because node.js doesn't automatically accept self-signed certificates but throws a `DEPTH_ZERO_SELF_SIGNED_CERT` error in this case.

For development environments however it is kind of typical to use "dummy" certificates for DEV or QA machines being available only inside the local corporate network. Thus ddm-tool should be able to handle this situation gracefully.

**Comment by emiloberg** [comment]
Just pushed version 0.8.6 which adds the setting `allowSelfSignedCerts` (bool).

Any new created projects will have this setting in its settings file (default set to `false`). To add the setting to a previously created projects, edit the json file of the project in `~/.ddmtool/config/projects` and just add the line `allowSelfSignedCerts: true`. 

Now the million dollar question: Does it work?

**Comment by jamesbarwick** [comment]
Works fine.  Thanks for the patch!

**Comment by jamesbarwick** [comment]
By the way....I spent over 6 hours trying to get a CA certificate loaded in NPM in the .npmrc file before I read the fine README.md file wish indicated this property settings.  My CA is self-signed, not the web site certificate...so...the self-sign was "in the chain.  Argh...teach me to read...lesson learned....
